#!/bin/bash
# Emit the authoritative task-reference table, derived from the task files.
#
#   bash scripts/gen-task-table.sh            # markdown table to stdout
#   bash scripts/gen-task-table.sh --counts   # just the headline counts
#   bash scripts/gen-task-table.sh --check    # verify docs match reality
#
# WHY THIS EXISTS: every doc that hand-wrote "18 tasks (7 lead, 7 coding,
# 4 marketing)" went stale the moment the topology changed, and nothing
# caught it because prose isn't testable. The repo already knows how many
# tasks exist and who owns them. Docs should quote this, not restate it.
#
# --check is wired into scripts/test/run.sh so drift fails the harness
# instead of shipping.
set -uo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
MODE="${1:-table}"

# group dir -> (label, model tier). Keep in sync with scripts/sync-tasks.sh.
group_label() {
  case "$1" in
    support)     echo "Lead|Claude Sonnet";;
    local)       echo "Local ops|local model";;
    engineering) echo "Reviewer|Claude Haiku";;
    marketing)   echo "Marketing|Claude";;
    *)           echo "?|?";;
  esac
}
group_dir() {
  case "$1" in
    support)     echo "support/community-support";;
    engineering) echo "engineering/community-coding";;
    marketing)   echo "marketing/community-marketing";;
    local)       echo "local/community-local";;
  esac
}

TOTAL=0; GATED=0; UNGATED=""
ROWS=""
for group in support local engineering marketing; do
  gdir=$(group_dir "$group")
  label=$(group_label "$group"); agent="${label%%|*}"
  for md in "$ROOT/$gdir"/ai.nanoco.nanoclaw/tasks/*.md; do
    [ -f "$md" ] || continue
    name=$(basename "$md" .md)
    sched=$(grep -m1 '^schedule:' "$md" | sed 's/^schedule: *//; s/"//g')
    if [ -f "$ROOT/scripts/tasks/$group/$name.sh" ]; then
      gate="yes"; GATED=$((GATED+1))
    else
      gate="no"; UNGATED="$UNGATED $name"
    fi
    TOTAL=$((TOTAL+1))
    ROWS="$ROWS| \`$name\` | $agent | \`$sched\` | $gate |
"
  done
done

counts() {
  printf '%s tasks across 4 agents; %s script-gated' "$TOTAL" "$GATED"
  [ -n "$UNGATED" ] && printf ' (ungated:%s)' "$UNGATED"
  printf '\n'
}

case "$MODE" in
  --counts) counts;;
  --state)
    # What each task PERSISTS, derived from its gate script. Answers the
    # question "what data does this build, and is it kept?" without anyone
    # having to read 17 shell scripts.
    #
    # Two classes, and the distinction is the one that matters operationally:
    #   CACHE  — a cursor, a heartbeat stamp, a last-seen snapshot. Losing it
    #            costs one duplicate report or one re-fetch. Rebuildable.
    #   LEDGER — append-only history that CANNOT be re-fetched retroactively
    #            (a follower count for last Tuesday is gone). Losing it is
    #            permanent data loss, so these are what backup exists for.
    echo "| Task | Agent | Writes | Class |"
    echo "|------|-------|--------|-------|"
    for group in support local engineering marketing; do
      gdir=$(group_dir "$group")
      label=$(group_label "$group"); agent="${label%%|*}"
      for md in "$ROOT/$gdir"/ai.nanoco.nanoclaw/tasks/*.md; do
        [ -f "$md" ] || continue
        name=$(basename "$md" .md)
        sh="$ROOT/scripts/tasks/$group/$name.sh"
        if [ ! -f "$sh" ]; then
          echo "| \`$name\` | $agent | _(no gate script — agent-written state only)_ | — |"
          continue
        fi
        files=$(grep -ohE '"\$DATA/[a-zA-Z0-9._-]+"' "$sh" 2>/dev/null \
                | tr -d '"$' | sed 's|DATA/||' | grep -v '^config\.env$' | sort -u)
        if [ -z "$files" ]; then
          echo "| \`$name\` | $agent | _nothing — stateless_ | — |"
          continue
        fi
        out=""; class=""
        for f in $files; do
          case "$f" in
            *.jsonl|*history*) c="LEDGER";;
            *)                 c="cache";;
          esac
          out="$out\`$f\` ($c)<br>"
          case "$c" in LEDGER) class="LEDGER";; *) [ -z "$class" ] && class="cache";; esac
        done
        echo "| \`$name\` | $agent | ${out%<br>} | $class |"
      done
    done
    echo
    echo "_LEDGER entries are append-only and unrecoverable if lost — they are what \`workspace-backup\` exists to protect. Everything marked cache is safe to delete; the task rebuilds it on its next run (at the cost of one duplicate report)._"
    echo "_Generated by \`scripts/gen-task-table.sh --state\` — do not hand-edit._";;
  --check)
    # The one number docs are allowed to state in prose is the total, and
    # only in the form this script prints. Anything else is drift.
    BAD=0
    for f in "$ROOT"/README.md "$ROOT"/docs/OPERATIONS.md "$ROOT"/docs/INSTALL.md; do
      [ -f "$f" ] || continue
      # Stale agent-count language. "the other three agents" and "three of the
      # four" are CORRECT when there are 4 — one of them is being excluded — so
      # exclude those forms rather than flagging honest prose. Only an
      # unqualified "three agents"/"all three templates" is drift.
      if grep -niE '(^|[^a-z])(all )?three (agents|templates)' "$f" \
           | grep -viE 'other three|three of the four|remaining three' >/dev/null; then
        echo "DRIFT $f: says 'three agents/templates' but there are 4"; BAD=1
      fi
      # stale task-count language: any "N of M tasks" or "all M tasks" where M != TOTAL
      while IFS= read -r m; do
        [ -z "$m" ] && continue
        [ "$m" = "$TOTAL" ] || { echo "DRIFT $f: task count '$m' should be $TOTAL"; BAD=1; }
      done < <(grep -ohE '(of|all) ([0-9]+) task' "$f" | grep -oE '[0-9]+')
    done
    # The ready-gate size is stated in CHECKPOINTS.md's own heading and quoted
    # by README.md and INSTALL.md. Three copies of one number drift the moment
    # a gate item is added — CHECKPOINTS is the authority.
    CP="$ROOT/docs/CHECKPOINTS.md"
    if [ -f "$CP" ]; then
      GATE=$(grep -oE 'ready gate — [0-9]+ points' "$CP" | grep -oE '[0-9]+' | head -1)
      if [ -n "$GATE" ]; then
        for f in "$ROOT/README.md" "$ROOT/docs/INSTALL.md"; do
          [ -f "$f" ] || continue
          while IFS= read -r n; do
            [ "$n" = "$GATE" ] || { echo "DRIFT $f: ready-gate count '$n' should be $GATE (CHECKPOINTS.md is authoritative)"; BAD=1; }
          done < <(grep -ohE '[0-9]+-point ready gate' "$f" | grep -oE '^[0-9]+')
        done
      fi
    fi

    if [ "$BAD" -eq 0 ]; then echo "task-table check OK: $(counts)"; fi
    exit $BAD;;
  *)
    echo "| Task | Agent | Schedule (UTC) | Script-gated |"
    echo "|------|-------|----------------|--------------|"
    printf '%s' "$ROWS"
    echo
    echo "_$(counts)_"
    echo "_Generated by \`scripts/gen-task-table.sh\` — do not hand-edit._";;
esac
